name: Publish Docker image for prod-env

on:
  push:
    branches:
      - master
      - feature/*
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:

jobs:
  push_to_registry:
    uses: ./.github/workflows/local-env-docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit
  arm:
    needs: push_to_registry
    runs-on: ubuntu-24.04-arm
    steps:
    - name: pull
      run: docker pull "ghcr.io/yam1xtest/pelican-ui:local-env-sha-${{ github.sha }}"

    - name: pull og
      run: docker pull ghcr.io/tourmalinecore/pelican-ui:local-env-latest

    - name: Inspect
      run: docker inspect "ghcr.io/yam1xtest/pelican-ui:local-env-sha-${{ github.sha }}"

    - name: Inspect og
      run: docker inspect ghcr.io/tourmalinecore/pelican-ui:local-env-latest

  amd:
    needs: push_to_registry
    runs-on: ubuntu-24.04
    steps:
    - name: pull
      run: docker pull "ghcr.io/yam1xtest/pelican-ui:local-env-sha-${{ github.sha }}"

    - name: pull og
      run: docker pull ghcr.io/tourmalinecore/pelican-ui:local-env-latest

    - name: Inspect
      run: docker inspect "ghcr.io/yam1xtest/pelican-ui:local-env-sha-${{ github.sha }}"

    - name: Inspect og
      run: docker inspect ghcr.io/tourmalinecore/pelican-ui:local-env-latest
