name: Reusable workflow example

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  push_to_registry:
    uses: Yam1xTest/pelican-ui/.github/workflows/local-env-docker-build-and-push.yml@feature/test-templates
    with: 
        test-build-args: CDN_ENABLED=false
