name: Publish Docker image for local-env 

# ToDo should it be triggered only as part of an open PR?
# currently it triggers for any commit in a FB
on: 
  push:
    branches:
      - feature/*
      
jobs:
  push_to_registry:
    permissions:
      packages: write
      contents: read
      attestations: write
    uses: "Yam1xTest/workflows/.github/workflows/local-env-docker-build-and-push.yml@${{ github.ref_name }}"
    with: 
      build-args: |
        CDN_ENABLED=false
      prefix: local-env-
    secrets: inherit
