name: Reusable workflow example

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/local-env-docker-build-and-push.yml
      with:
        test-build-args: CDN_ENABLED=false
